# Only execute CI on main branch
branches:
  only:
    - main

language: node_js

node_js:
  - node # Latest stable release

env:
  - PLAYWRIGHT_BROWSERS_PATH=0 # Install Playwright browser binaries in node_modules

install:
  - npm ci

script:
  - ng build --prod --base-href https://ardis.lu/
  - cp dist/ardis-lu-frontend/index.html dist/ardis-lu-frontend/404.html # To simulate server-side URL redirect on gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/ardis-lu-frontend
  fqdn: ardis.lu
  on:
    branch: main